<?php
	$f ='<div class="orders" id="freight"><div class="blue">FREIGHT INFORMATION</div>';
	$f.='<ul>';
	$f.='<li class="hdr">';
	$f.='<span class="s3">Box Sizes</span>';
	$f.='<span class="s3">Max</span>';
	$f.='<span class="s3">Box Fees</span>';
	$f.='<span class="s4">Naturelles</span>';
	$f.='<span class="s4">Application Kits</span>';
	$f.='<span class="s4">Non-DLC Products</span></li>';
	$f.='<li>';
	$f.='<span class="s3"></span>';
	$f.='<span class="s3"></span>';
	$f.='<span class="s3"></span>';
	$f.='<span class="s4 smaller">free freight @</span>';
	$f.='<span class="s4 smaller">free freight @</span>';
	$f.='<span class="s4">P 70.00 per kilo</span></li>';
	$f.='<li>';
	$f.='<span class="s3">SMALL</span>';
	$f.='<span class="s3">5 Kg</span>';
	$f.='<span class="s3">P 150.00</span>';
	$f.='<span class="s4">23 boxes</span>';
	$f.='<span class="s4">10 boxes</span>';
	$f.='<span class="s4"><em>Breville Products</em></span></li>';
	$f.='<li>';
	$f.='<span class="s3">MEDIUM</span>';
	$f.='<span class="s3">10 Kg</span>';
	$f.='<span class="s3">P 200.00</span>';
	$f.='<span class="s4">68 boxes</span>';
	$f.='<span class="s4">15 boxes</span>';
	$f.='<span class="s4"><em>Bread Premixes</em></span></li>';
	$f.='<li>';
	$f.='<span class="s3"></span>';
	$f.='<span class="s3"></span>';
	$f.='<span class="s3"></span>';
	$f.='<span class="s4"></span>';
	$f.='<span class="s4"></span>';
	$f.='<span class="s4"><em>Wines</em></span></li>';
	$f.='</ul></div>';
	$freight=$f;
?>
